#!/usr/bin/env node
/**
 * THIRD-PARTY-NOTICES 生成器：从生产依赖图读取 license 声明，
 * 生成 THIRD-PARTY-NOTICES.md（借鉴 ZCode licenses.mjs 的轻量版）。
 * 用法：node scripts/generate-notices.mjs（发布前跑一次，或依赖变更后跑）
 */
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;

const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'));
const deps = Object.keys(pkg.dependencies ?? {});

const lines = [
  '# Third-Party Notices',
  '',
  'This product includes software developed by third parties under the licenses listed below.',
  'Generated by `node scripts/generate-notices.mjs` from the production dependency graph.',
  '',
];

for (const name of deps.sort()) {
  const manifestPath = join(ROOT, 'node_modules', name, 'package.json');
  if (!existsSync(manifestPath)) {
    lines.push(`## ${name}`, '', '> 未安装（node_modules 中不存在），跳过', '');
    continue;
  }
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  const license = manifest.license ?? 'UNKNOWN';
  const version = manifest.version ?? '?';
  const homepage = manifest.homepage ?? manifest.repository ?? '';
  lines.push(
    `## ${name} v${version}`,
    '',
    `- License: ${typeof license === 'string' ? license : JSON.stringify(license)}`,
    homepage ? `- Homepage: ${homepage}` : '',
    '',
  );
}

await writeFile(join(ROOT, 'THIRD-PARTY-NOTICES.md'), lines.filter((l) => l !== '').join('\n') + '\n', 'utf8');
console.log(`THIRD-PARTY-NOTICES.md 已生成（${deps.length} 个生产依赖）`);
